name: Rename Folder

on:
  workflow_dispatch: # 手动触发工作流
    inputs:
      old_folder: # 旧文件夹名称
        description: 'Old folder name (e.g., old_folder)'
        required: true
      new_folder: # 新文件夹名称
        description: 'New folder name (e.g., new_folder)'
        required: true

jobs:
  rename-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rename folder
        run: |
          git mv ${{ github.event.inputs.old_folder }} ${{ github.event.inputs.new_folder }}
        shell: bash

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git commit -m "Rename folder from ${{ github.event.inputs.old_folder }} to ${{ github.event.inputs.new_folder }}"
          git push
        shell: bash
